title: Audrey DECK # your name (or website title) here
logo: "/images/photo_de_profil.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Etudiante en M2 Technologie des Langues à l'Université de Strasbourg, je suis passionnée des nouvelles technologies et plus particulièrement par le domaine de la programmation. 
  Vous pouvez découvrir mes différents projets dans ce portfolio !
  <br><br>
  Portfolio en cours de construction
  <br><br>
  <a href="https://www.linkedin.com/in/audrey-deck-a12141199/">Mon profil LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-179504831-1 # your Google Analytics tracking ID here
