title: Audrey DECK # your name (or website title) here
logo: "/images/photo_de_profil.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Etudiante en M2 Technologie des Langues à l'Université de Strasbourg, je suis passionnée des nouvelles technologies et plus particulièrement par le domaine de la programmation.
  <br><br>
  Vous pouvez découvrir mes différents projets artistiques dans ce portfolio !
  <br><br>
  <a href="https://www.linkedin.com/in/audrey-deck-a12141199/"><font color="#6a2c70>Mon profil LinkedIn</font></a>
  
theme: jekyll-theme-minimal
google_analytics: UA-179504831-1 # your Google Analytics tracking ID here
